name: Java Server CI Workflow with Maven

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: maven
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/respository
          key: ${{ runner.os }}-m2-${{ hashFiles('eladmin/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Package with Maven
        run: cd eladmin && mvn -B package --file pom.xml -Dmaven.test.skip=true -P prod
      - run: mkdir stashing && cp eladmin/eladmin-system/target/eladmin-system-1.1.jar stashing
      - name: Automatic Release 
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.PERSONAL_TOKEN }} 
          automatic_release_tag: "{{ github.ref }} - ${{ github.event.head_commit.message }}"
          prerelease: false # 是否为预发布版本
          title: "Release {{ github.ref }} - ${{ github.event.head_commit.message }}"
          files: |
            stashing/eladmin-system-1.1.jar.jar
      # - name: Deploy with Maven
      #   uses: garygrossgarten/github-action-scp@release
      #   with:
      #     local: "eladmin/eladmin-system/target/eladmin-system-1.1.jar"
      #     remote: "/root/admin"
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      # - name: Restart Server
      #   if: always()
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     script: |
      #       cd /root/admin
      #       ./restart.sh
